name: OrgaQuant
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.6
  - pip
  - pylint
  - pip:
    - tensorflow-gpu==1.14
    - keras-resnet==0.2.0
    - h5py
    - cython
    - keras
    - matplotlib
    - opencv-python>=3.3.0
    - numpy>=1.14
    - pandas
    - trackpy
    - conda-pack
    - jupyter
    - jupyter_contrib_nbextensions
    - ipywidgets
    - git+https://github.com/UMCU-BeekmanLab/OrgaQuant